"""Backward-compatible re-exports — prefer backend.services.parsers.helpers.hardware_signals."""

from backend.services.parsers.helpers.hardware_signals import *  # noqa: F403
from backend.services.parsers.helpers.hardware_signals import (
    BEARING_DESIGNATION_RE,
    DIMENSION_AXIAL_RE,
    FASTENER_PREFIX_RE,
    FASTENER_TYPE_RE,
    FASTENER_TYPES,
    HARDWARE_KEYWORD_RE,
    HARDWARE_KEYWORDS,
    HARDWARE_TERMS,
    IMPERIAL_THREAD_RE,
    LENGTH_CM_RE,
    LENGTH_IN_RE,
    LENGTH_MM_RE,
    METRIC_FASTENER_RE,
    METRIC_SIZE_WORD_RE,
    METRIC_SIZES,
    METRIC_THREAD_RE,
    extract_metric_sizes,
    has_axial_dimension,
    has_bearing_designation,
    has_fastener_prefix,
    has_fastener_suffix,
    has_fastener_type,
    has_hardware_keyword,
    has_hardware_signal,
    has_imperial_thread,
    has_length_cm,
    has_length_in,
    has_length_mm,
    has_metric_fastener,
    has_metric_size,
)

__all__ = [
    "BEARING_DESIGNATION_RE",
    "DIMENSION_AXIAL_RE",
    "FASTENER_PREFIX_RE",
    "FASTENER_TYPE_RE",
    "FASTENER_TYPES",
    "HARDWARE_KEYWORD_RE",
    "HARDWARE_KEYWORDS",
    "HARDWARE_TERMS",
    "IMPERIAL_THREAD_RE",
    "LENGTH_CM_RE",
    "LENGTH_IN_RE",
    "LENGTH_MM_RE",
    "METRIC_FASTENER_RE",
    "METRIC_SIZE_WORD_RE",
    "METRIC_SIZES",
    "METRIC_THREAD_RE",
    "extract_metric_sizes",
    "has_axial_dimension",
    "has_bearing_designation",
    "has_fastener_prefix",
    "has_fastener_suffix",
    "has_fastener_type",
    "has_hardware_keyword",
    "has_hardware_signal",
    "has_imperial_thread",
    "has_length_cm",
    "has_length_in",
    "has_length_mm",
    "has_metric_fastener",
    "has_metric_size",
]
