"""Shared BOM parsing helpers (site-agnostic)."""

from backend.services.parsers.helpers.bom_line import parse_hardware_line
from backend.services.parsers.helpers.bom_quantities import parse_quantity_and_name, strip_line_prefix
from backend.services.parsers.helpers.bom_sections import find_section_lines
from backend.services.parsers.helpers.hardware_signals import (
    BEARING_DESIGNATION_RE,
    DIMENSION_AXIAL_RE,
    FASTENER_TYPE_RE,
    HARDWARE_KEYWORD_RE,
    HARDWARE_KEYWORDS,
    HARDWARE_TERMS,
    IMPERIAL_THREAD_RE,
    METRIC_FASTENER_RE,
    METRIC_SIZES,
    METRIC_THREAD_RE,
    extract_metric_sizes,
    has_axial_dimension,
    has_bearing_designation,
    has_fastener_prefix,
    has_fastener_suffix,
    has_fastener_type,
    has_hardware_keyword,
    has_hardware_signal,
    has_imperial_thread,
    has_length_cm,
    has_length_in,
    has_length_mm,
    has_metric_fastener,
    has_metric_size,
)
from backend.services.parsers.helpers.html_text import (
    collapse_blank_lines,
    collapse_inline_whitespace,
    html_to_text,
)
from backend.services.parsers.helpers.marketplace import (
    MARKETPLACE_NOISE,
    SKIP_PROSE_LINE,
    clean_name_and_spec,
    marketplace_note_suffix,
    strip_marketplace_tokens,
)
from backend.services.parsers.helpers.parts_merge import merge_parts

__all__ = [
    "BEARING_DESIGNATION_RE",
    "DIMENSION_AXIAL_RE",
    "FASTENER_TYPE_RE",
    "HARDWARE_KEYWORD_RE",
    "HARDWARE_KEYWORDS",
    "HARDWARE_TERMS",
    "IMPERIAL_THREAD_RE",
    "MARKETPLACE_NOISE",
    "METRIC_FASTENER_RE",
    "METRIC_SIZES",
    "METRIC_THREAD_RE",
    "SKIP_PROSE_LINE",
    "clean_name_and_spec",
    "collapse_blank_lines",
    "collapse_inline_whitespace",
    "extract_metric_sizes",
    "find_section_lines",
    "has_axial_dimension",
    "has_bearing_designation",
    "has_fastener_prefix",
    "has_fastener_suffix",
    "has_fastener_type",
    "has_hardware_keyword",
    "has_hardware_signal",
    "has_imperial_thread",
    "has_length_cm",
    "has_length_in",
    "has_length_mm",
    "has_metric_fastener",
    "has_metric_size",
    "html_to_text",
    "marketplace_note_suffix",
    "merge_parts",
    "parse_hardware_line",
    "parse_quantity_and_name",
    "strip_line_prefix",
    "strip_marketplace_tokens",
]
